version: "3.9"

services:

  # =========================
  # MIGRATIONS (RODA UMA VEZ)
  # =========================
  migrate:
    build: .
    container_name: finansilva_migrate
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONUNBUFFERED: "1"
    working_dir: /app/src
    volumes:
      - ./src:/app/src
    entrypoint: /entrypoint.migrate.sh
    command: python manage.py migrate --noinput

  # =========================
  # DJANGO WEB
  # =========================
  web:
    build: .
    container_name: finansilva_web
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONUNBUFFERED: "1"
    working_dir: /app/src
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    entrypoint: /entrypoint.no-migrate.sh
    command: python manage.py runserver 0.0.0.0:8000

  # =========================
  # CELERY WORKER
  # =========================
  celery:
    build: .
    container_name: finansilva_celery
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONUNBUFFERED: "1"
    working_dir: /app/src
    volumes:
      - ./src:/app/src
    entrypoint: /entrypoint.no-migrate.sh
    command: celery -A core worker -l info

  # =========================
  # CELERY BEAT
  # =========================
  beat:
    build: .
    container_name: finansilva_celery_beat
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONUNBUFFERED: "1"
    working_dir: /app/src
    volumes:
      - ./src:/app/src
    entrypoint: /entrypoint.no-migrate.sh
    command: celery -A core beat -l info

  # =========================
  # FLOWER
  # =========================
  flower:
    build: .
    container_name: finansilva_flower
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
    working_dir: /app/src
    volumes:
      - ./src:/app/src
    ports:
      - "5555:5555"
    entrypoint: /entrypoint.no-migrate.sh
    command: celery -A core flower --port=5555

  # =========================
  # REDIS
  # =========================
  redis:
    image: redis:7-alpine
    container_name: finansilva_redis
    ports:
      - "6379:6379"

networks:
  default:
    name: finansilva_net